name: gestao_fhd
description: Gestão FHD - App de gestão empresarial para FHD Automação Industrial

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # Biometric Authentication
  local_auth: ^2.1.8
  local_auth_android: ^1.0.38
  local_auth_ios: ^1.1.5
  
  # File Handling
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # UI Enhancements
  flutter_animate: ^4.3.0
  
  # Device Info
  device_info_plus: ^9.1.2
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Timezone
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/ 