name: whatsapp_notifier
description: App para receber notificações e enviar para WhatsApp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.2
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 